version: '3'

services:
  app:
    build: RUN apt-get update && apt-get install -y mysql-client

    stdin_open: true  # docker run -i
    tty: true         # docker run -t

    depends_on:
      db:
        condition: service_healthy
    environment:
      - CI=${CI}  # Pass CI environment variable from the host to the container
    stop_grace_period: "2m"
    networks:
      - app-network


  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge
