
@startuml
!theme plain

left to right direction
actor Employee as e

rectangle "Population Information System" {

  usecase "Show Countries by Population" as UC1
  usecase "Show Continents by Population" as UC2
  usecase "Show Regions by Population" as UC3
  usecase "Top N Populated Countries" as UC4
  usecase "Top N Populated Cities" as UC5
  usecase "View Capital Cities by Population" as UC6
  usecase "Urban vs. Rural Population" as UC7
  usecase "View Population in Region" as UC8
  usecase "View Language Speakers" as UC9
  usecase "Calculate Percentage of Language Speakers" as UC10

  UC9 ..> UC10 : "<<include>>"

}

e --> UC1 : "queries"
e --> UC2 : "queries"
e --> UC3 : "queries"
e --> UC4 : "specifies N"
e --> UC5 : "specifies N"
e --> UC6 : "selects scope"
e --> UC7 : "selects area"
e --> UC8 : "chooses region"
e --> UC9 : "selects language"
e --> UC10 : "requires calculation"

@enduml
